# Generated by Django 4.2.6 on 2023-10-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
