# Generated by Django 4.2.6 on 2023-10-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '7'), ('9', '8'), ('10', '10'), ('11', '11')], max_length=2)),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('opening_date', models.DateField()),
            ],
        ),
    ]
