# Generated by Django 4.2.6 on 2023-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmodel',
            name='grade',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '7'), ('9', '8'), ('10', '10'), ('11', '11')]),
        ),
    ]
