# Generated by Django 4.2.6 on 2023-10-23 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_classesmodel_school_schoolsmodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesmodel',
            name='grade',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (8, '7'), (9, '8'), (10, '10'), (11, '11')]),
        ),
        migrations.AlterField(
            model_name='classesmodel',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.schoolsmodel'),
        ),
    ]
